version: "3"

services:
  app:
    container_name: node-express-api
    restart: on-failure
    build: .
    depends_on:
      - postgres_express_api
    environment:
      NODE_ENV: development
    env_file:
      - .env.development
    ports:
      - 3000:3000
    command: npm run dev
    volumes:
      - .:/usr/app/
    networks:
      - web_app

  postgres_express_api:
    image: postgres:16
    ports:
      - 35432:5432
    environment:
      POSTGRES_USER: express_api
      POSTGRES_PASSWORD: express_api
      POSTGRES_DB: express_api
    networks:
      - web_app

networks:
  web_app:
